### ISSUE TITLE
Package on Nuget.org?

### ISSUE THREAD

**Issue by imercerwillow** [fallin/gexf-dotnet#4]
Readme says there is one but I'm drawing a blank on nuget.org.

**Comment by fallin** [comment]
Install-Package gexf-dotnet -Version 0.2.1

I haven't released a v1.0 yet, but I will soon.

**Comment by fallin** [comment]
OK, v1.0.0 is released, so you should be able to find the NuGet package without enabling the "pre-release" checkbox in the VS package manager. This should make it easier to find.
